[package]
name = "eijirs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
clap = { version = "4.5.57", features = ["derive"] }
color-eyre = "0.6.5"
dirs = "6.0.0"
encoding_rs = "0.8.35"
encoding_rs_io = "0.1.7"
ratatui = "0.30.0"
sled = "0.34.7"
tui-input = "0.15.0"
