[package]
name = "eijirs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
clap = { version = "4.5.57", features = ["derive"] }
dirs = "6.0.0"
encoding_rs = "0.8.35"
encoding_rs_io = "0.1.7"
sled = "0.34.7"
